### ISSUE TITLE
Data-trigger: why do we need the active sleep here?

### ISSUE THREAD

**Issue by chrberger** [Adam2092/Urho3D.VehicleRemoteControl#1]
https://github.com/Adam2092/Urho3D.VehicleRemoteControl/blob/8b1533b1868314fea02402307c30c42d625c210c/src/CameraViewer.cpp#L73

**Comment by Adam2092** [comment]
Thanks for the good comment. I didn't realize "data-trigger" at first as there's no OD4Session involved here, and a delay was a subconscious thought, which seems unnecessary now.
