### ISSUE TITLE
Why does the consumer need to notify other processes?

### ISSUE THREAD

**Issue by chrberger** [Adam2092/Urho3D.VehicleRemoteControl#2]
https://github.com/Adam2092/Urho3D.VehicleRemoteControl/blob/8b1533b1868314fea02402307c30c42d625c210c/src/CameraViewer.cpp#L115

**Comment by Adam2092** [comment]
Thanks for the comment. Initially I thought everyone having access to the shm should notify others whenever the I/O process is finished and the shm is unlocked. I double checked your tutorial again and found that consumers would not need to call the notify() function.
